[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
UPLOAD_DIR = "uploads"
